# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: shiny-deploy

on:
  push:
    branches:
      - shiny-server-main
      - release

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      CONDA_ENV_NAME: "conda_env"
#      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Install libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev
 
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v1

      - name: Install rsconnect
        shell: Rscript {0}
        run: install.packages(c("rsconnect", "yaml", "reticulate"))
        
      - name: Conda
        shell: Rscript {0}
        run: |
          library(yaml)
          library(rsconnect)
          library(reticulate)
          environment<-read_yaml("environment.yml")
          # expression to find pip
          dependencies <- environment$dependencies
          pip_index <- ("pip"==sapply(dependencies, function(x) names(x)))
          # the items in 'dependencies' NOT under 'pip'
          packages <- unlist(dependencies[which(!pip_index)])
          # add in the items under 'pip'
          # packages <- c(packages, dependencies[which(pip_index)][[1]]$pip)
          env_name<-Sys.getenv("CONDA_ENV_NAME")
          message("About to call 'conda_create'")
          conda_create(
           envname = env_name,
           packages = packages,
           forge = TRUE,
           channel = environment$channels
          )
          message("About to call 'py_install'")
          use_condaenv(condaenv=env_name)
          py_install("tabletext")
          py_install("schematicpy", pip=TRUE)
          message("Done with 'py_install'")
        
      - name: Create config file
        run: |
          echo "CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}" > confg.yml    
          echo "CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}" >> confg.yml
          echo "CONDA_ENV_NAME: ${{ env.CONDA_ENV_NAME }}" >> confg.yml
          # TODO Autogenerate the app' name at the end of the URL:
          echo "APP_URL: https://sagebio.shinyapps.io/data_curator-staging" >> confg.yml
 
      - name: Authorize and deploy app
        shell: Rscript {0}
        run: |
          branch<-Sys.getenv("GITHUB_REF_NAME")
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]
          if (!startsWith(branch, "release")) {
             appName = paste(appName, "staging", sep="-")
          }
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}", "${{ secrets.RSCONNECT_TOKEN }}", "${{ secrets.RSCONNECT_SECRET }}")
          rsconnect::deployApp(appName = appName)
 